export const tripConstants = {
    GET_PROPERTY_REQUEST : "GET_PROPERTY_REQUEST",
    GET_PROPERTY_SUCCESS : "GET_PROPERTY_SUCCESS"
};

export const customerConstants = {
    REGISTER_CUSTOMER_REQUEST : "REGISTER_CUSTOMER_REQUEST",
    REGISTER_CUSTOMER_SUCCESS : "REGISTER_CUSTOMER_SUCCESS",
    REGISTER_CUSTOMER_FAILURE : "REGISTER_CUSTOMER_FAILURE",
    CUSTOMER_LOGIN_REQUEST : "CUSTOMER_LOGIN_REQUEST",
    CUSTOMER_LOGIN_SUCCESS : "CUSTOMER_LOGIN_SUCCESS",
    CUSTOMER_LOGIN_FAILURE : "CUSTOMER_LOGIN_FAILURE",
    FORGOT_PASSWORD_REQUEST : "FORGOT_PASSWORD_REQUEST",
    FORGOT_PASSWORD_SUCCESS : "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAILURE : "FORGOT_PASSWORD_FAILURE",
    RESET_PASSWORD_REQUEST : "RESET_PASSWORD_REQUEST",
    RESET_PASSWORD_SUCCESS : "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILURE : "RESET_PASSWORD_FAILURE",
    VERIFY_EMAIL_REQUEST : "VERIFY_EMAIL_REQUEST",
    VERIFY_EMAIL_SUCCESS : "VERIFY_EMAIL_SUCCESS",
    VERIFY_EMAIL_FAILURE : "VERIFY_EMAIL_FAILURE",
    GET_CUSTOMER_DETAILS_REQUEST : "GET_CUSTOMER_DETAILS_REQUEST",
    GET_CUSTOMER_DETAILS_SUCCESS : "GET_CUSTOMER_DETAILS_SUCCESS",
    GET_CUSTOMER_DETAILS_FAILURE : "GET_CUSTOMER_DETAILS_FAILURE",
    CUSTOMER_LOGOUT_SUCCESS: "CUSTOMER_LOGOUT_SUCCESS",
};

export const myAccountConstants = {
    UPDATE_PROFILE_REQUEST : "UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_SUCCESS : "UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAILURE : "UPDATE_PROFILE_FAILURE",
    REFRESH_MY_PROFILE_STATE_SUCCESS: "REFRESH_MY_PROFILE_STATE_SUCCESS"
};