import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';

const Trip = ({ ...props }) => {
    const { trips } = props;
    const [tripList, setTripList] = useState([]);

    useEffect(() => {
        const { getTrips } = props;
        const getTripsData = getTrips();
    }, [])

    useEffect(() => {
        if (trips.length > 0) {
            setTripList(trips);
        }
    }, [trips])

    return (
        <div className={styles.container}>
            <Head>
                <title>Trips</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Trips</a>
                </h1>
            </main>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Trips List
                </h1>
                {tripList?.length && tripList.map((trip, index) => {
                    return (
                        <p key={index}>{trip.title}</p>
                    )
                })}
            </main>


            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Trip;